theme = "github_light"

[editor]
auto-format  = true
bufferline   = "multiple"
mouse        = false
rulers       = [ 100 ]
scroll-lines = 0
scrolloff    = 10
text-width   = 100
true-color   = true

[editor.file-picker]
# true = ignore files which are ignored / hidden; false = show them
git-exclude = false
git-global  = true
git-ignore  = false
hidden      = false
ignore      = true

[editor.indent-guides]
character   = "▏"
render      = true

[editor.statusline]
left   = [ "mode", "spinner", "read-only-indicator", "file-modification-indicator" ]
center = [ "file-name", "separator", "file-type" ]
right  = [ "diagnostics", "selections", "register", "position", "version-control" ]

[editor.whitespace.render]
tab = "all"

[keys.insert]
up       = "no_op"
down     = "no_op"
left     = "no_op"
right    = "no_op"
pageup   = "no_op"
pagedown = "no_op"
home     = "no_op"
end      = "no_op"

[keys.normal]
up       = "no_op"
down     = "no_op"
left     = "no_op"
right    = "no_op"
pageup   = "no_op"
pagedown = "no_op"
home     = "no_op"
end      = "no_op"
