[[language]]
name = "c"
file-types = ["c", "h"]
indent = { unit = "\t", tab-width = 8 }

[[language]]
name = "cpp"
# Copy of upstream, minus 'h' as we want those to be interpreted as C.
# https://github.com/helix-editor/helix/blob/f0be627dcb5b9f780a4bfa6ae012370d7c41d3be/languages.toml#L625
file-types = ["cc", "hh", "c++", "cpp", "hpp", "ipp", "tpp", "cxx", "hxx", "ixx", "txx", "ino", "C", "H", "cu", "cuh", "cppm", "h++", "ii", "inl", { glob = ".hpp.in" }, { glob = ".h.in" }]

[[language]]
name = "go"
language-servers = [ "gopls" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls-plus"]

[[language]]
name = "python"
auto-format = true

[[language]]
name = "text"
scope = "text.txt"
roots = []
language-servers = [ "ltex-ls-plus" ]
file-types = [ "txt" ]
auto-format = false
text-width = 100

[language-server.gopls]
command = "gopls"
args = ["-logfile=/tmp/gopls.log",  "serve"]

[language-server.gopls.config]
"ui.diagnostic.staticcheck" = true
"ui.diagnostic.analyses" = { ST1000 = false }

[language-server.ltex-ls-plus.config.ltex.disabledRules]
"en-US" = [ "PROFANITY", "ARROWS", "WHITESPACE_RULE" ]

[language-server.ltex-ls-plus.config.ltex.dictionary]
"en-US" = [ "gorouter", "ltex-ls", "Alacritty", "CCEE", "VXLAN", "Unicast", "routable", "IaaS", "VNet" ]
