#!/usr/bin/env zsh

# git
alias g="git"
alias ga="git add"
alias gc="git commit"
alias gd="git diff"
alias gf="git fetch"
alias gl="git pull"
alias gp="git push"
alias gr="git rebase"
alias gs="git status"
alias gam="git commit --amend --no-edit"
alias gau="git add -u"
alias gco="git checkout"
alias gds="git diff --staged"
alias grb="git rebase \"\$(git merge-base origin/HEAD HEAD)\""
alias gst="git stash"
alias gsu="git submodule update --recursive"
alias gsw="git switch"
alias ggprah="git log --all --decorate --oneline --graph"
alias glast="git log --reverse --oneline --decorate=no \"\$(git merge-base origin/HEAD HEAD)\"..HEAD"
alias glog="git log"
alias gplease="git push --force-with-lease"

function gsww() {
  # If not ( `gsw <branch>` OR `gsw -c <branch>` ) AND is multi-worktree
  if ! [[ ( "${#}" -eq 1 || ( "${#}" -eq 2 && "${1}" -eq "-c" ) ) && "$(git worktree list | wc -l)" -gt 1 ]]; then
    # not a multi-worktree repository or non-standard usage of gsw
    git switch "${@}"
    return
  fi

  target_dir=""
  if [[ "${1}" = "-c" ]]; then
    target_dir="$(git rev-parse --show-toplevel)/../$(basename "${2}")"
    git worktree add -b "${2}" "${target_dir}"
  else
    target_dir="$(git rev-parse --show-toplevel)/../$(basename "${1}")"
    git worktree add "${target_dir}" "${1}"
  fi
  cd "${target_dir}"
}

# ls
alias ls="ls --color=auto --time-style=+'%Y-%m-%d %H:%M'"
alias l="ls -lh"
alias ll="ls -lhA"
alias la="ls -lha"

# python
alias pip="python3 -m pip"
alias pip-purge="python3 -m pip uninstall -y -r <(pip freeze --exclude-editable)"
alias venv="python3 -m venv"
alias venvv="python3 -m venv venv && source ./venv/bin/activate"

# container
alias k="kubectl"
alias d="docker"
alias dc="docker compose"

# iTerm
if [[ "${TERM_PROGRAM}" = "iTerm.app" ]]; then
  alias it2dl="bash <(curl -s https://iterm2.com/utilities/it2dl)"
  alias it2ul="bash <(curl -s https://iterm2.com/utilities/it2ul)"
fi

# Linux
if [[ "${OSTYPE}" =~ "linux" ]]; then
  alias ip="ip -c=auto"
fi

# Darwin
if [[ "${OSTYPE}" =~ "darwin" ]]; then
  alias idea="open -na 'IntelliJ IDEA.app' --args"
  alias typora="open -a typora"
fi

# other
alias cdr='cd $(git rev-parse --show-toplevel)'
alias scp="scp -o 'RemoteCommand=none'"
alias 2fa="ykman oath accounts code --single"
function cht.sh() { curl -s "cht.sh/${1:-}?style=xcode" | less -R; }

rgzf() {
  rg \
    --color=always \
    --line-number \
    --no-heading \
    --smart-case \
    "${@:-.}" \
  | fzf \
    --ansi \
    --color "hl:-1:underline,hl+:-1:underline:reverse" \
    --delimiter : \
    --preview 'bat --color=always {1} --highlight-line {2}' \
    --preview-window '60%,border-bottom,+{2}+3/3,~3' \
    --header "Return: Helix; ^O: Open" \
    --layout reverse \
    --bind 'enter:become(hx {1}:{2}),ctrl-o:execute-silent(git gh open file {1} {2}),c:execute-silent(git gh open -p file {1} {2} | pbcopy)'
}

pandox() {
  # TODO: find a good way to copy to clipboard across different OSes
  RESULT="$(pbpaste | pandoc -f "${1:?from required}" -t "${2:?to required}")";
  if [[ -n "${RESULT}" ]]; then
      pbcopy <<< "${RESULT}";
  fi
}

# managing this configuration
dotf() {
  if ! test -L ~/.zshenv; then
    echo "dotfiles not managed by stow"
    return 1
  fi
  __stow_dir="$(realpath "$(dirname "${HOME}/$(readlink "${HOME}/.zshenv")")/..")"

  stow --dotfiles -d "${__stow_dir}" -t ~ "${@}"
}
