#!/usr/bin/env zsh

export NIX_HASH="4bb072f0a8b267613c127684e099a70e1f6ff106"

function nsh() {
	nix shell "nixpkgs/${NIX_HASH}#${1?Please provide the package name as first argument}"
}

function command_not_found_handler() {
	package_name="${1}"
	if nix eval --raw "nixpkgs/${NIX_HASH}#${package_name}" &> /dev/null; then
		nix shell "nixpkgs/${NIX_HASH}#${package_name}" -c "${@}"
	else
		echo "${package_name}: command not found, not even in nix"
	fi
}

