#!/usr/bin/env zsh

# if on macOS we might need to add some executables brew refuses to link
# (brew refuses to link them because macOS already provides those binaries
# but they are older versions)
[[ -d '/usr/local/opt/sqlite/bin' ]] && export PATH="/usr/local/opt/sqlite/bin:${PATH}"
[[ -d '/usr/local/opt/openssl@1.1/bin' ]] && export PATH="/usr/local/opt/openssl@1.1/bin:${PATH}"
[[ -d '/usr/local/opt/ruby/bin' ]] && export PATH="/usr/local/opt/ruby/bin:${PATH}"
[[ -d '/usr/local/opt/curl/bin' ]] && export PATH="/usr/local/opt/curl/bin:${PATH}"
[[ -d '/usr/local/opt/gnu-sed/libexec/gnubin' ]] && export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:${PATH}"
