#!/usr/bin/env zsh

# System
export PATH="${HOME}/.local/bin:${PATH}"
export XDG_CONFIG_HOME="${HOME}/.config"

# Go
export GOCACHE="${HOME}/.cache/go"
export GOMODCACHE="${HOME}/.cache/go-mod"
export GOBIN="${HOME}/.local/bin"

# tt
export TT_HOME_DIR="${HOME}/.config/tt"
