#!/usr/bin/env zsh

autoload -Uz compinit
compinit

# lower-case matches upper-case as well
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

bindkey -e

# man 1 zshoptions
setopt EXTENDED_HISTORY
setopt HASH_LIST_ALL
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_NO_STORE
setopt PROMPT_SUBST
setopt SHARE_HISTORY

# man 1 zshparam
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
HISTSIZE=2000
SAVEHIST=2000
