#!/usr/bin/env zsh

# git
alias g="git"
alias ga="git add"
alias gc="git commit"
alias gd="git diff"
alias gl="git pull"
alias gp="git push"
alias gr="git rebase"
alias gs="git status"
alias gt="git branch -u origin/\$(git rev-parse --abbrev-ref HEAD)" # set the local branch to track the remote branch on origin with the same name
alias gam="git commit --amend --no-edit"                            # amend a change to the last commit without changing the commit message
alias gco="git checkout"
alias grb="git rebase -i \"\$(git merge-base origin/HEAD HEAD)\""   # start an interactive rebase for all commits of the feature branch
alias gsu="git submodule update --recursive"                        # update all sub-modules
alias gsw="git switch"
alias ggprah="git log --all --decorate --oneline --graph"           # show a nice history
alias glast="git log -1"
alias glog="git log"
alias gplease="git push --force-with-lease"

# ls
alias ls="ls --color=auto"
alias l="ls -lh"
alias ll="ls -lhA"
alias la="ls -lha"

# python
alias pip="python3 -m pip"
alias pip-purge="python3 -m pip uninstall -y -r <(pip freeze --exclude-editable)"
alias venv="python3 -m venv"
alias venvv="python3 -m venv venv && source ./venv/bin/activate"

# container
alias k="kubectl"
alias d="docker"
alias dc="docker compose"

# iTerm
if [[ "${TERM_PROGRAM}" = "iTerm.app" ]]; then
  alias it2dl="bash <(curl -s https://iterm2.com/utilities/it2dl)"
  alias it2ul="bash <(curl -s https://iterm2.com/utilities/it2ul)"
fi

# Linux
if [[ "${OSTYPE}" =~ "linux" ]]; then
  alias ip="ip -c=auto"
fi

# Darwin
if [[ "${OSTYPE}" =~ "darwin" ]]; then
  alias idea="open -na 'IntelliJ IDEA.app' --args"
  alias typora="open -a typora"
fi

# other
alias scp="scp -o 'RemoteCommand=none'"

# managing this configuration
alias dotfiles="git -C '${HOME}' --git-dir .dotfiles"

