#!/usr/bin/env bash

source ~/.profile

__prompt_command() {
    local last_status=$?

    # First line: [hostname] [status] directory
    local prepend_space=false
    PS1=''

    if [[ $SHLVL -gt 1 ]]; then
        PS1+="\[\e[31m\][lvl=$((SHLVL - 1))]\[\e[0m\] "
    fi

    PS1+='\[\e[31m\]\h\[\e[0m\]:\e[38;5;18m\w\[\e[0m\]'

    if [[ $last_status -ne 0 ]]; then
        PS1+=" \[\e[31m\]${last_status}\[\e[0m\] "
    fi

    PS1+='\n'

    # Second line: $ or #
    if [[ $EUID -eq 0 ]]; then
        PS1+='\[\e[34m\]#\[\e[0m\] '
    else
        PS1+='\[\e[34m\]\$\[\e[0m\] '
    fi
}

PROMPT_COMMAND=__prompt_command
