#!/usr/bin/env bash

alias ls='ls --color=auto'

source ~/.profile

__prompt_command() {
    local last_status=$?

    # First line: [hostname] [status] directory
    local prepend_space=false
    PS1=''

    if [[ $SHLVL -gt 1 ]]; then
        PS1+="\[\e[31m\][lvl=$((SHLVL - 1))]\[\e[0m\] "
    fi

    PS1+='\[\e[31m\]\h\[\e[0m\]:\e[38;5;18m\w\[\e[0m\]'

    if [[ $last_status -ne 0 ]]; then
        PS1+=" \[\e[31m\]${last_status}\[\e[0m\] "
    fi

    PS1+='\n'

    # Second line: $ or #
    if [[ $EUID -eq 0 ]]; then
        PS1+='\[\e[34m\]#\[\e[0m\] '
    else
        PS1+='\[\e[34m\]\$\[\e[0m\] '
    fi
}

PROMPT_COMMAND=__prompt_command

# Set title to the working directory, and briefly to "wdir | command" while a
# command is running.
__wdir() {
    case "$PWD" in
        "$HOME") printf '~' ;;
        *)       printf '%s' "${PWD##*/}" ;;
    esac
}
__title() { printf '\033]2;%s\033\\' "$1"; }

PROMPT_COMMAND="__title \"\$(__wdir)\"; $PROMPT_COMMAND; __title_armed=1"
trap '[ "$__title_armed" = 1 ] && __title_armed=0 && __title "$(__wdir) │ ${BASH_COMMAND:0:50}"' DEBUG
