theme = "github_light"

[editor]
auto-format = true
bufferline = "multiple"
mouse = false
rulers = [100]
scroll-lines = 0
scrolloff = 10
text-width = 100

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
skip-levels = 0
