theme = "onelight"

[editor]
bufferline = "multiple"
mouse = false
rulers = [100]
scrolloff = 10
text-width = 100
true-color = true

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
skip-levels = 0
