abbr -a -- d docker
abbr -a -- dc 'docker compose'
abbr -a -- g git
abbr -a -- ga 'git add'
abbr -a -- gam 'git commit --amend --no-edit'
abbr -a -- gau 'git add -u'
abbr -a -- gc 'git commit'
abbr -a -- gco 'git checkout'
abbr -a -- gd 'git diff'
abbr -a -- gds 'git diff --staged'
abbr -a -- gf 'git fetch'
abbr -a -- ggraph 'git log --all --decorate --oneline --graph'
abbr -a -- gl 'git pull'
abbr -a -- gp 'git push'
abbr -a -- gplease 'git push --force-with-lease'
abbr -a -- gr 'git rebase'
abbr -a -- gs 'git status'
abbr -a -- gst 'git stash'
abbr -a -- gsu 'git submodule update --recursive'
abbr -a -- gsw 'git switch'
abbr -a -- k kubectl
abbr -a -- l 'ls -lh'
abbr -a -- ll 'ls -lha'
abbr -a -- p podman
abbr -a -- pip 'python3 -m pip'
abbr -a -- scp 'scp -o RemoteCommand=none'
abbr -a -- venv 'python3 -m venv'
abbr -a -- venvv 'python3 -m venv && source ./venv/bin/activate'
